"""Search top passages for a topic query across current FAISS article indices.

Run:
    python -m embedding_pipeline.topic_passage_search_demo --query musician --top-k 5
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np

try:
    import faiss  # type: ignore[import-not-found]
except Exception:
    faiss = None

from db.models import Article, CitationPassage, FaissPassageMap
from db.session import get_session
from embedding_pipeline.vector_index import embed_text


def _load_summary(summary_path: Path) -> list[dict[str, Any]]:
    if not summary_path.exists():
        raise FileNotFoundError(f"summary.json not found: {summary_path}")
    payload = json.loads(summary_path.read_text(encoding="utf-8"))
    return payload.get("articles", [])


def _resolve_article_id(article_url: str) -> int | None:
    session = get_session()
    try:
        row = session.query(Article.article_id).filter(Article.url == article_url).one_or_none()
        return int(row[0]) if row else None
    finally:
        session.close()


def _lookup_passage_text(article_id: int, index_file: str, row_id: int) -> str | None:
    session = get_session()
    try:
        mapping = (
            session.query(FaissPassageMap)
            .filter(FaissPassageMap.article_id == article_id)
            .filter(FaissPassageMap.index_file == index_file)
            .filter(FaissPassageMap.faiss_row_id == row_id)
            .one_or_none()
        )
        if mapping is None or not mapping.passage_key:
            return None

        citation_id = None
        passage_id = None
        if "_" in mapping.passage_key:
            left, right = mapping.passage_key.split("_", 1)
            if left.isdigit():
                citation_id = int(left)
            if right.isdigit():
                passage_id = int(right)

        query = session.query(CitationPassage)
        if passage_id is not None:
            query = query.filter(CitationPassage.passage_id == passage_id)
        if citation_id is not None:
            query = query.filter(CitationPassage.citation_id == citation_id)

        row = query.one_or_none()
        return row.content if row else None
    finally:
        session.close()


def search_top_passages(
    query: str,
    top_k: int,
    summary_path: Path,
    index_dir: Path,
) -> list[dict[str, Any]]:
    if faiss is None:
        raise RuntimeError("faiss is not installed in this environment")

    articles = _load_summary(summary_path)
    if not articles:
        return []

    query_vec = np.array([embed_text(query)], dtype="float32")
    hits: list[dict[str, Any]] = []

    for article in articles:
        index_file = article.get("index_file", "")
        article_url = article.get("article_url", "")
        article_title = article.get("article_title", "unknown")
        if not index_file or not article_url:
            continue

        article_id = _resolve_article_id(article_url)
        if article_id is None:
            continue

        index_path = index_dir / index_file
        if not index_path.exists():
            continue

        index = faiss.read_index(str(index_path))
        scores, indices = index.search(query_vec, max(1, top_k))
        for score, idx in zip(scores[0], indices[0]):
            if int(idx) < 0:
                continue
            hits.append(
                {
                    "article_id": article_id,
                    "article_title": article_title,
                    "article_url": article_url,
                    "index_file": index_file,
                    "faiss_row_id": int(idx),
                    "score": float(score),
                }
            )

    hits.sort(key=lambda h: h["score"], reverse=True)

    resolved: list[dict[str, Any]] = []
    for hit in hits:
        text = _lookup_passage_text(
            article_id=hit["article_id"],
            index_file=hit["index_file"],
            row_id=hit["faiss_row_id"],
        )
        if not text:
            continue

        resolved.append({**hit, "text": text})
        if len(resolved) >= top_k:
            break

    return resolved


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Read top passages for a semantic topic query from FAISS indices",
    )
    parser.add_argument("--query", default="musician", help="Semantic query string")
    parser.add_argument("--top-k", type=int, default=5, help="Number of passages to return")
    parser.add_argument(
        "--summary",
        default="vector_indices/summary.json",
        help="Path to summary.json generated by the pipeline",
    )
    parser.add_argument(
        "--index-dir",
        default="vector_indices",
        help="Directory containing .faiss index files",
    )
    args = parser.parse_args()

    results = search_top_passages(
        query=args.query,
        top_k=max(1, args.top_k),
        summary_path=Path(args.summary),
        index_dir=Path(args.index_dir),
    )

    print(f"Query: {args.query}")
    print(f"Top {max(1, args.top_k)} passages:\n")
    if not results:
        print("No passages found. Ensure summary/index files exist and DB mapping is populated.")
        return

    for rank, item in enumerate(results, 1):
        preview = " ".join(item["text"].split())
        print(f"{rank}. [{item['score']:.4f}] {item['article_title']}")
        print(f"   {preview[:240]}{'...' if len(preview) > 240 else ''}")
        print()


if __name__ == "__main__":
    main()
